adminUser: admin
adminPassword: "admin123!"

service:
  type: NodePort
  nodePort: 32000

persistence:
  enabled: true
  size: 2Gi
  storageClassName: local-path

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

sidecar:
  dashboards:
    enabled: true

dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 32
      datasource: Prometheus

