apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://github.com/lizseo/k8s-gitops-practice.git
      targetRevision: main
      path: monitoring/grafana
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      # 재현성 위해 차트 버전 명시 권장 (예: "8.6.0")
      # targetRevision: "<CHART_VERSION>"
      helm:
        releaseName: grafana
        valueFiles:
          - $values/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

