apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lizseo/k8s-gitops-practice.git'
    targetRevision: HEAD
    path: monitoring/prometheus
    helm:
      chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      valueFiles:
        - values.yaml        # Prometheus
        - ../grafana/values.yaml  # Grafana
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

