apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true  
spec:
  project: default
  sources: 
    - repoURL: https://prometheus-community.github.io/helm-charts 
      chart: kube-prometheus-stack                               
      targetRevision: 76.4.1                                     
      helm:
        releaseName: monitoring
        skipCrds: true
        valueFiles:
          - $values/monitoring/monitoring/values.yaml
    - repoURL: https://github.com/lizseo/k8s-gitops-practice.git
      targetRevision: HEAD
      ref: values          
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ApplyOutOfSyncOnly=true
      - SkipCRDs=true

