apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql-ha
      targetRevision: 16.3.1 
      helm:
        valueFiles:
          - $values/database/postgresql-ha/values.yaml 
    - repoURL: https://github.com/lizseo/k8s-gitops-practice.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

