apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lizseo/k8s-gitops-practice.git'
    targetRevision: main
    path: database/postgresql-ha
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

