apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-ha
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql-ha
    targetRevision: 14.0.2
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/lizseo/k8s-gitops-practice/main/database/postgresql-ha/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

