apiVersion: v1
kind: Secret
metadata:
  name: postgresql-ha-credentials
  namespace: database
type: Opaque
stringData:
  postgresql-password: "pguser123"
  postgresql-postgres-password: "super123"
  repmgr-password: "repmgr123"
  pgpool-password: "pgpool123"
  sr-check-password: "srcheck123"

