global:
  storageClass: "local-path" 
postgresql:
  replicaCount: 2
  existingSecret: postgresql-ha-credentials
  persistence:
    enabled: true
    storageClass: "local-path"  
    size: 2Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  podAntiAffinityPreset: soft
pgpool:
  replicaCount: 2
  existingSecret: postgresql-ha-credentials
  adminUsername: admin
  srCheck:
    username: sr_check_user
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
service:
  type: ClusterIP

