postgresql:
  replicaCount: 2
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  image:
   pullSecrets: []


persistence:
  enabled: true
  size: 8Gi

pgpool:
  replicaCount: 2
  adminPassword: 2EpE73CaIx
  image:
    pullSecrets: []

repmgr:
  password: kCtdCLmWs6

witness:
  create: false
  
metrics:
  enabled: false
  image:
    pullSecrets: []

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r76
    pullPolicy: IfNotPresent
    pullSecrets: []
