postgresql:
  replicaCount: 2
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

persistence:
  enabled: true
  size: 8Gi

pgpool:
  replicaCount: 2

repmgr:
  password: kCtdCLmWs6
