apiVersion: v2
name: prometheus-stack
description: Umbrella chart to deploy kube-prometheus-stack
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 62.7.0 
    repository: https://prometheus-community.github.io/helm-charts

