alertmanager:
  enabled: true
  persistentVolume:
    enabled: false

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

server:
  retention: 7d
  service:
    type: ClusterIP
  persistentVolume:
    enabled: true
    size: 20Gi
    storageClass: local-path

